### Sample request
POST http://localhost:8080/services/hello

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hel="http://learnwebservices.com/services/hello">
                   <soapenv:Header/>
                   <soapenv:Body>
                      <hel:HelloRequest>
                         <hel:Name>John Doe</hel:Name>
                      </hel:HelloRequest>
                   </soapenv:Body>
                </soapenv:Envelope>

### Sample bad request
POST https://apps.learnwebservices.com/services/hello

<soapenv:Envelope

### WSDL
GET http://localhost:8080/services/hello?WSDL

### Actuator / Health
GET http://localhost:8080/actuator/health

### Actuator / Info
GET http://localhost:8080/actuator/info